name: Dev Deploy

on:
  push:
    branches:
      - "main"
      - "dev"
  workflow_call:
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    if: false 
    secrets: inherit
  deploy:
    name: Dev Deploy
    #needs: test
    if: success()
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev 
      dockerPlatformName: linux/amd64
      productName: SwiftLambda
      lambdaName: swift-lambda-sample
    secrets: inherit
